name: Update Data

on:
  schedule:
    - cron: '*/10 * * * *' # Uruchamia co 10 minut
  workflow_dispatch: # Umozliwia reczne uruchomienie z githuba

jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
      FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python script
        run: python update_data.py

      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Automated update of schedule and substitutions" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/${{ github.repository }}
          git push origin main
